name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build App
        run: ./gradlew :app:assembleDebug --no-build-cache

      - uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

  android-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: lintDebug
        run: ./gradlew lint

      - uses: actions/upload-artifact@v3
        with:
          name: android-lint-report
          path: ~/**/build/reports/lint-results*.html
#
#  detekt:
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout
#        uses: actions/checkout@v4
#
#      - name: Set up JDK
#        uses: actions/setup-java@v3
#        with:
#          java-version: 17
#          distribution: 'zulu'
#
#      - name: detekt
#        run: ./gradlew detektCheck
#
#      - uses: actions/upload-artifact@v3
#        with:
#          name: detekt-report
#          path: ./**/build/reports/detekt/detekt.*
#
#  spotless:
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout
#        uses: actions/checkout@v4
#
#      - name: Set up JDK
#        uses: actions/setup-java@v3
#        with:
#          java-version: 17
#          distribution: 'zulu'
#
#      - name: detekt
#        run: ./gradlew spotlessCheck
#
#      - uses: actions/upload-artifact@v3
#        with:
#          name: detekt-report
#          path: ./**/build/reports/detekt/detekt.*
#
#  unit-test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout
#        uses: actions/checkout@v4
#
#      - name: Set up JDK
#        uses: actions/setup-java@v3
#        with:
#          java-version: 17
#          distribution: 'zulu'
#
#      - name: unitTest
#        run: ./gradlew test -x konsist_test:test
#
#      - uses: actions/upload-artifact@v3
#        with:
#          name: unit-test-report
#          path: ./**/build/reports/tests/